name: Request Unity Activation File
on: workflow_dispatch
jobs:
  activation:
    runs-on: ubuntu-latest
    steps:
      - uses: game-ci/unity-request-activation-file@v2
        id: request
        with:
          unityVersion: 6000.0.80f1
      - uses: actions/upload-artifact@v4
        with:
          name: unity-activation-file
          path: ${{ steps.request.outputs.filePath }}
